services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    networks:
      - backend-network

  fastapi:
    build:
      context: ./fastApiProject
      dockerfile: Dockerfileapi
    container_name: api
    volumes:
      - ./fastApiProject:/fastApiProject
      - images:/images
    depends_on:
      - mongodb
    networks:
      - backend-network
      - frontend-network
    environment:
      - ENV=production

  reactapp:
    build:
      context: ./reactapp
      dockerfile: Dockerfilereact
    container_name: react
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://ai-explorer.tech/api
    networks:
      - frontend-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certificates/fullchain.pem:/etc/nginx/certificates/fullchain.pem
      - ./certificates/privkey.pem:/etc/nginx/certificates/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - reactapp
      - fastapi
    networks:
      - frontend-network
      - backend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mongodb-data:
  images:
